version: "2.1"
services:
  trash-guides-sync:
    image: losojos27/trash-guides-sync
    container_name: trash-guides-sync
    network_mode: bridge
    logging:
      driver: json-file
    environment:
      - PUID=1050
      - PGID=100
      - TZ=America/Chicago
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    volumes:
      - "/volume1/docker/appdata/trash-guides-sync/trash.yml:/usr/local/bin/trash.yml"
    restart: unless-stopped